version: "3.2"
services:
  mysql:
    image: mysql:5.7.28
    restart: always
    container_name: loris_mysql
    ports:
        - "8082:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=neopass
    networks:
      loris_net:
        ipv4_address: 172.28.1.2

  apache-php:
    build:
        context: .
        dockerfile: Dockerfile_php
    container_name: loris_apache
    restart: always
    ports:
      - "8088:80"
    volumes:
      - ./dicom_in/:/data/loris/dicom_in
      - ./dicom_post/:/data/loris/dicom_post
      - ./nifti_out/:/data/loris/nifti_out
    links:
       - mysql
    depends_on:
       - mysql
    networks:
      loris_net:
        ipv4_address: 172.28.1.1

networks:
  loris_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
